services:
  app:
    build: ./
    container_name: apiserver
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./configs:/configs
  db:
    image: postgres:16
    container_name: db_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "./migrations", "-database", "postgres://postgres:123@db:5432/rest_dev?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy